name: python_lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
            with:
              commit_message: Apply Code Formatter Change
              ref: ${{ github.head_ref }}
