name: python_unittest
on: [push, pull_request]

jobs:
    formatter:
        name: unittest
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.9.0]
        steps:
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
          - name: unittest
            run: python -m unittest "tests/*.py"

